apiVersion: v1
kind: Service
metadata:
  name: {{ include "weavcraft.fullname" . }}
  labels:
    {{- include "weavcraft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      nodePort: {{ .Values.service.externalPort }}
  selector:
    {{- include "weavcraft.selectorLabels" . | nindent 4 }}
