apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.ingress.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "meta.helm.sh/release-name": {{ .Release.Name | quote }}
    "meta.helm.sh/release-namespace": {{ .Release.Namespace | quote }}
    "helm.sh/resource-policy": keep
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  issuerRef:
    name: {{ .Values.ingress.tls.certManager.issuerName }}
    kind: {{ ternary "ClusterIssuer" "Issuer" (eq .Values.ingress.tls.certManager.issuerType "cluster-issuer") }}
  commonName: {{ (first .Values.ingress.hosts).host }}
  dnsNames:
    {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
    {{- end }}
  renewBefore: 240h
