{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "proj.name" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "proj.name" . }}
    {{- include "proj.selectorLabels" . | nindent 4 }}
    {{- include "proj.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}  # 循環遍歷 deployments 配置
    {{- $hosts := . }}  # 循環遍歷 deployments 配置
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}  # 遍歷 paths 配置
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ .serviceName | quote }}
                port:
                  number: {{ .servicePort }}
          {{- end }}
    {{- end }}
  tls:
    {{- if .Values.ingress.tls.enabled }}
    - hosts:
        {{- range .Values.ingress }}  # 循環部署來設置 TLS 主機
        {{- $ingress := . }}  # 循環遍歷 deployments 配置
        - {{ .host | quote }}
        {{- end }}
      secretName: {{ .Values.ingress.tls.secretName | quote }}  # 使用的 TLS 憑證
    {{- end }}
{{- end }}
