apiVersion: v1
kind: Service
metadata:
  name: {{ include "proj.name" . }}-ingress
  labels:
    app.kubernetes.io/name: {{ include "proj.name" . }}-ingress
    {{- include "proj.labels" $ | nindent 4 }}  # 正確縮進
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: {{ include "proj.name" . }}-ingress
    {{- include "proj.selectorLabels" $ | nindent 4 }}  # 正確縮進
  ports:
    - protocol: TCP
      port: 80  # HTTP
      targetPort: 31013
    # 如果需要啟用 HTTPS，可以解除註解下面的部分
    # - protocol: TCP
    #   port: 443  # HTTPS
    #   targetPort: 31012
