{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rfjs.serviceAccountName" . }}
  labels:
    {{- include "rfjs.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  namespace: default
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
secrets:
  - name: harbor-registry-secret