name: Release pnpm project

on:
  workflow_call:
    secrets:
      GIT_TOKEN:
        required: true
    outputs:
        release-version:
          value: ${{ jobs.release.outputs.release-version }}

jobs:
  release:
    # This job is used to release the package using standard-version
    name: Run release
    runs-on: ubuntu-latest
    # environment: actions
    outputs:
      release-version: ${{ steps.version.outputs.current-version }}
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}
      
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          

      - name: Initialization
        id: init
        run: |
          git config --global user.email royfuwei@gmail.com
          git config --global user.name royfuwei
          pnpm -v
          pnpm install --frozen-lockfile

      - name: Update Version
        run: |
          npx standard-version
      
      - name: Release Tag
        run: |
          git push --follow-tags origin HEAD:production -f

      - name: Get Package Version
        id: version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
      
      
