name: Publish pnpm package to NPM

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      GIT_TOKEN:
        required: true
      NPM_TOKEN:
        required: true

jobs:
  publish:
    name: Publish pnpm package to npm
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GIT_TOKEN }}

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      # Set up the Node.js environment
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Build
        run: |
          pnpm -v
          pnpm install --frozen-lockfile
          pnpm test
          pnpm build

      - uses: JS-DevTools/npm-publish@v1
        with:
          package: ./dist/package.json
          access: public
          token: ${{ secrets.NPM_TOKEN }}
  