name: Deploy Local RFJS API

on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      projectSource:
        required: true
        type: string
      appVersion:
        required: true
        type: string
      helmVersion:
        required: true
        type: string
      config-path:
        description: 'Path to the configuration file'
        required: true
        type: string
    secrets:
      HARBOR_HOST:
        required: true
      HARBOR_USERNAME:
        required: true
      HARBOR_TOKEN:
        required: true
      envPAT:
        required: true

jobs:
  release-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.envPAT }}
          configuration-path: ${{ inputs.config-path }}

      - name: Helm Setup
        uses: azure/setup-helm@v3
        with:
          version: 3.14.0

      - uses: pyTooling/Actions/with-post-step@v0.4.5
        with:
          main: |
            echo "Logging in to ${{ secrets.HARBOR_HOST }} ..."
            helm registry login \
              --username ${{ secrets.HARBOR_USERNAME }} \
              --password ${{ secrets.HARBOR_TOKEN }} \
              ${{ secrets.HARBOR_HOST }}

          post: |
            echo "Logging out of ${{ secrets.HARBOR_HOST }} ..."
            helm registry logout ${{ secrets.HARBOR_HOST }}

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: royfuwei/rfjs-devops
          fetch-depth: 0
          token: ${{ secrets.envPAT }}

      - name: Push Helm Chart
        env:
          HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
        run: |
          echo $HARBOR_HOST
          cd ${{ inputs.projectName }}
          ls -la
          sed -i 's/'tag:' .*/'tag:' ${{ inputs.appVersion }}/g' ./helm/values.yaml
          sed -i 's/'appVersion:' .*/'appVersion:' ${{ inputs.appVersion }}/g' ./helm/Chart.yaml
          sed -i 's/'version:' .*/'version:' ${{ inputs.helmVersion }}/g' ./helm/Chart.yaml
          cat ./helm/values.yaml
          cat ./helm/Chart.yaml
          tar zcvf ${{ inputs.projectName }}.tgz helm
          helm push ${{ inputs.projectName }}.tgz oci://harbor.royfuwei.dev/${{ inputs.projectSource }}