name: Deploy Local RFJS API

on:
  workflow_call:
    inputs:
      config-path:
        description: 'Path to the configuration file'
        required: true
        type: string
    secrets:
      HARBOR_HOST:
        required: true
      HARBOR_USERNAME:
        required: true
      HARBOR_TOKEN:
        required: true
      envPAT:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.envPAT }}
        configuration-path: ${{ inputs.config-path }}
        
  release-helm:
    runs-on: ubuntu-latest
    needs: triage
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.envPAT }}
          configuration-path: ${{ inputs.config-path }}

      - name: Helm Setup
        uses: azure/setup-helm@v3
        with:
          version: 3.14.0

      # - name: Login to Harbor Registry
      #   uses: central-x/helm-login-action@v1
      #   with:
      #     registry: ${{ secrets.HARBOR_HOST }}
      #     username: ${{ secrets.HARBOR_USERNAME }}
      #     password: ${{ secrets.HARBOR_TOKEN }}
      - uses: pyTooling/Actions/with-post-step@v0.4.5
        with:
          main: |
            echo "Logging in to ${{ secrets.HARBOR_HOST }} ..."
            helm registry login \
              --username ${{ secrets.HARBOR_USERNAME }} \
              --password ${{ secrets.HARBOR_TOKEN }} \
              ${{ secrets.HARBOR_HOST }}

          post: |
            echo "Logging out of ${{ secrets.HARBOR_HOST }} ..."
            helm registry logout ${{ secrets.HARBOR_HOST }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: royfuwei/rfjs-devops
          fetch-depth: 0
          token: ${{ secrets.envPAT }}

      - name: Push Helm Chart
        env:
          HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
          HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
        run: |
          echo $HARBOR_HOST
          cd rfjs-api
          tar zcvf rfjs-api.tgz helm
          ls -la
          helm push rfjs-api.tgz oci://harbor.royfuwei.dev/royfuwei